config/routes.rb
Rails.application.routes.draw do
  
  root 'tops#index'
  get '/privacy', to: 'tops#privacy'
  get '/terms', to: 'tops#terms'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  delete 'log_out', to: 'sessions#destroy', as: 'log_out'

  resources :users, only: %i[show]
  resources :sessions, only: %i[create destroy]
  resource :profile, only: %i[show edit update]
  
  resources :posts do
    resource :like, only: %i[create destroy]
    collection do
      get 'search'
      get 'category/:category_id', action: :category, as: :category
    end
    member do
      get 'channel'
    end
    resources :answers, only: %i[create]
  end
  resources :questions, only: %i[show] do
    get 'random', on: :collection, to: 'questions#random'
    get 'start', on: :collection, to: 'questions#start'
  end
  resources :albums
  mount ActionCable.server => '/cable'
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :initialize_session
  before_action :set_user, only: %i[start]

  def show
    post_history = session[:post_history] || []
    session.delete(:answered_count)
    session.delete(:post_history)
    puts "回答数: #{session[:answered_count]}" 
    puts "質問履歴: #{post_history.inspect}"
    @user = current_user
    current_user.calculate_status
    @most_user = User.most_user.name
    @user_info = User.find_by(name: @most_user)
  end

  def edit; end


  def start
    return unless logged_in? 
  end  

  def random
    post_history = session[:post_history] || []
    @post = select_random_post(post_history)
    @answer = Answer.new
    current_user.calculate_status
    session[:post_history] << @post.id

    if session[:post_history].size > 10
      session[:post_history].shift(session[:post_history].size - 10)
    end
    session[:post_history] ||= [] # セッション履歴が存在しない場合に初期化

    post_history = session[:post_history]
    @post_number = post_history.size
    puts "Session ID: #{session.id}"
    
  end

  private

  def select_random_post(post_history)
    # 履歴に含まれていない質問をランダムに選択
    available_posts = Post.where.not(id: post_history)
    if available_posts.empty?
      # 履歴に含まれている質問がすべて表示された場合、履歴をクリア
      post_history.clear
      available_posts = Post.all # すべての質問を再び利用可能な質問として設定
    end
    selected_post = available_posts.order('RANDOM()').first
    # 選択した質問がnilでないか確認.使用可能な質問がない場合は、全質問の中からランダムに選択
    selected_post || Post.order('RANDOM()').first
  end
  
  def initialize_session
    session[:post_history] ||= []
  end  

  def find_question
    @post = current_user.posts.find(params[:id])
  end

  def set_user
    return unless logged_in?
    @user = User.find(current_user.id)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/random.html.erb
<div class="flex items-center justify-center h-screen">
    <div class="text-center border border-gray-300 rounded-lg p-4">
        <h1 class="text-2xl md:text-4xl lg:text-5xl font">あるある話</h1><br>
        <h1 class="text-ms md:text-ms lg:text-ms font">その<%= @post_number %>/10問中</h1>
        <p class="question text-lg md:text-xl lg:text-2xl font-bold text-gray-800 mb-4 font"><%= @post.content %></p>
        <%# <%= "Current User Status: #{current_user.status}" %> 
        <div class="flex items-center justify-center space-x-4">
            <%= form_with model: @answer, url: post_answers_path(@post), method: :post,  data: { turbo: false } do |f| %>
                <%= f.hidden_field :answer_select, value: "yes" %>
                <%= f.submit "共感" , class: "py-3 px-4 gap-4 mr-4 rounded-md border border-transparent font-semibold bg-gray-500 text-white hover:bg-gray-600 focus:outline-none focus:ring-2 focus:ring-gray-500 focus:ring-offset-2 transition-all text-sm dark:bg-gray-700 dark:hover:bg-gray-600 dark:focus:ring-offset-gray-800"%>
            <% end %>
            <div class="w-4"></div> 
            <%= form_with model: @answer, url: post_answers_path(@post), method: :post,  data: { turbo: false } do |f| %>
                <%= f.hidden_field :answer_select, value: "no" %>
                <%= f.submit "共感しない", class: "py-3 px-4 gap-2 rounded-md border border-transparent font-semibold bg-yellow-500 text-white hover:bg-yellow-600 focus:outline-none focus:ring-2 focus:ring-yellow-500 focus:ring-offset-2 transition-all text-sm dark:focus:ring-offset-gray-800" %>
            <% end %>
        </div>
    </div>
</div>

app/views/questions/show.html.erb
<div class="flex justify-center items-center min-h-screen channel bg-green-50" style="background-image: url(<%= asset_path('bg.png') %>)">
    <div class="flex justify-center"> 
        <%= link_to posts_path, class: "bg-gray-300 hover:bg-gray-400 text-gray-800 font-bold py-2 px-4 rounded inline-flex items-center font" do %>
            <span>仲間のところへ</span>
        <% end %>
        <div class="border bg-white border-gray-300 p-8 rounded-lg">
            <h1 class="text-xl font-semibold mb-2 font">あなたの共感度</h1>
            <% if @user.avatar.present? %>
                <%= image_tag @user.avatar.url, class: "inline-block w-20 h-20 rounded-full"%>
            <% elsif @user.image.present? %> 
                <%= image_tag @user.image, class: "inline-block w-20 h-20 rounded-full" %>
            <% else %>
                <span class="inline-block h-[2.375rem] w-[2.375rem] bg-gray-100 rounded-full overflow-hidden">
                    <svg class="h-full w-full text-gray-300" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <rect x="0.62854" y="0.359985" width="15" height="15" rx="7.5" fill="white"/>
                        <path d="M8.12421 7.20374C9.21151 7.20374 10.093 6.32229 10.093 5.23499C10.093 4.14767 9.21151 3.26624 8.12421 3.26624C7.0369 3.26624 6.15546 4.14767 6.15546 5.23499C6.15546 6.32229 7.0369 7.20374 8.12421 7.20374Z" fill="currentColor"/>
                        <path d="M11.818 10.5975C10.2992 12.6412 7.42106 13.0631 5.37731 11.5537C5.01171 11.2818 4.69296 10.9631 4.42107 10.5975C4.28982 10.4006 4.27107 10.1475 4.37419 9.94123L4.51482 9.65059C4.84296 8.95684 5.53671 8.51624 6.30546 8.51624H9.95231C10.7023 8.51624 11.3867 8.94749 11.7242 9.62249L11.8742 9.93184C11.968 10.1475 11.9586 10.4006 11.818 10.5975Z" fill="currentColor"/>
                    </svg>
                </span>
            <% end %>
            <div class="grow">
                <span class="block text-xl font-semibold text-gray-800 dark:text-gray-800"><%= @user.name %></span>
            </div>
            <div class="flex w-full h-4 bg-gray-200 rounded-full overflow-hidden dark:bg-gray-200 mt-4">
                <% if @user.status > 50 %>
                    <div class="flex flex-col justify-center overflow-hidden bg-blue-500 text-xs text-white text-center" role="progressbar" style="width: <%= @user.status %>%; min-width: 10%;" aria-valuenow="<%= @user.status %>" aria-valuemin="0" aria-valuemax="100">
                        <%= @user.status >= 0 ? @user.status : 0 %>
                    </div>
                <% elsif @user.status > 30 %>
                    <div class="flex flex-col justify-center overflow-hidden bg-yellow-300 text-xs text-white text-center" role="progressbar" style="width: <%= @user.status %>%; min-width: 10%;" aria-valuenow="<%= @user.status %>" aria-valuemin="0" aria-valuemax="100">
                        <%= @user.status >= 0 ? @user.status : 0 %>
                    </div>
                <% else %> 
                    <div class="flex flex-col justify-center overflow-hidden bg-red-600 text-xs text-white text-center" role="progressbar" style="width: <%= @user.status %>%; min-width: 10%;" aria-valuenow="<%= @user.status %>" aria-valuemin="0" aria-valuemax="100">
                        <%= @user.status >= 0 ? @user.status : 0 %>
                    </div>
                <% end %>
            </div>
        </div>
    </div> 
</div>
<div data-controller="comment-modal" data-comment-modal-target="modal" class="text-center">
    <div class="fixed inset-0 flex items-center justify-center z-50">
        <div class="modal-container bg-yellow-300 w-96 p-4 rounded-lg shadow-lg z-50">
            <div class="modal-content" data-comment-modal-target="content">
                <div class="flex justify-center mt-4">
                    <div class="border bg-white border-gray-300 p-8 rounded-lg font text-xl">
                        <p>共感が多かったお相手</p>
                        <div class="ml-6 mt-6 flex flex-col items-center">
                                <%= link_to user_path( @user_info), class: "hover:bg-gray-200 hover:text-blue-500" do %>
                                    <% if   @user_info.avatar.present? %>
                                        <%= image_tag  @user_info.avatar.url, class: "inline-block h-20 w-20 rounded-full"%>
                                    <% elsif  @user_info.image.present? %> 
                                        <%= image_tag  @user_info.image, class: "inline-block h-30 w-20" %>
                                    <% else %>
                                        <span class="inline-block h-[2.375rem] w-[2.375rem] bg-gray-100 rounded-full overflow-hidden">
                                            <svg class="h-full w-full text-gray-300" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                                                <rect x="0.62854" y="0.359985" width="15" height="15" rx="7.5" fill="white"/>
                                                <path d="M8.12421 7.20374C9.21151 7.20374 10.093 6.32229 10.093 5.23499C10.093 4.14767 9.21151 3.26624 8.12421 3.26624C7.0369 3.26624 6.15546 4.14767 6.15546 5.23499C6.15546 6.32229 7.0369 7.20374 8.12421 7.20374Z" fill="currentColor"/>
                                                <path d="M11.818 10.5975C10.2992 12.6412 7.42106 13.0631 5.37731 11.5537C5.01171 11.2818 4.69296 10.9631 4.42107 10.5975C4.28982 10.4006 4.27107 10.1475 4.37419 9.94123L4.51482 9.65059C4.84296 8.95684 5.53671 8.51624 6.30546 8.51624H9.95231C10.7023 8.51624 11.3867 8.94749 11.7242 9.62249L11.8742 9.93184C11.968 10.1475 11.9586 10.4006 11.818 10.5975Z" fill="currentColor"/>
                                            </svg>
                                        </span>
                                    <% end %>
                                    <div class="text-2xl">
                                        <%=   @most_user %>さん
                                    </div>
                                <% end %>
                        
                            <%= image_tag 'let.png', class: "ml-6 w-30 h-30" %>
                        </div>
                    </div>
                </div>
            </div>
            <button data-action="click->comment-modal#close" data-turbo-frame="modal" ><i class="fa-solid fa-xmark"></i></button>
        </div>
    </div>

</div>

app/views/questions/start.html.erb
<div class="flex justify-center items-center min-h-screen">
    <%=link_to random_questions_path,  data: { turbo: false }, class: "box1 inline-flex justify-center items-center font-semibold text-white focus:outline-none focus:ring-3 focus:ring-gray-500 focus:ring-offset-2 transition-all text-sm dark:focus:ring-offset-gray-800" do %>
        仲間とマッチング
    <% end %>
</div>