config/routes.rb
Rails.application.routes.draw do
  
  root 'tops#index'
  get '/privacy', to: 'tops#privacy'
  get '/terms', to: 'tops#terms'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  delete 'log_out', to: 'sessions#destroy', as: 'log_out'

  resources :users, only: %i[show]
  resources :sessions, only: %i[create destroy]
  resource :profile, only: %i[show edit update]
  
  resources :posts do
    resource :like, only: %i[create destroy]
    collection do
      get 'search'
      get 'category/:category_id', action: :category, as: :category
    end
    member do
      get 'channel'
    end
    resources :answers, only: %i[create]
  end
  resources :questions, only: %i[show] do
    get 'random', on: :collection, to: 'questions#random'
    get 'start', on: :collection, to: 'questions#start'
  end
  resources :albums
  mount ActionCable.server => '/cable'
end

app/models/albam.rb
class Albam < ApplicationRecord
    belongs_to :user

    validates :title, presence: true, length: { maximum: 255 }
    validates :introduction, length: { maximum: 655 }
    validates :albam_image, presence: true
    
    mount_uploader :albam_image, AlbamImageUploader


end

app/models/album.rb
class Album < ApplicationRecord
    belongs_to :user

    validates :title, presence: true, length: { maximum: 255 }
    validates :introduction, length: { maximum: 655 }
    validates :album_image, presence: true

    mount_uploader :album_image, AlbumImageUploader
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :post
  
  enum answer_select: { yes: 0, no: 1 }
  
  scope :yes_count, -> { where(answer_select: 'yes').count }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :posts, dependent: :destroy

    validates :name, presence: true, uniqueness: true
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :post

    validates :user_id, uniqueness: { scope: :post_id }
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :post

  after_create_commit { MessageBroadcastJob.perform_later self }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :likes, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :answers
  

  validates :content, presence: true, length: { maximum: 255 }
  validates :user_id, presence: true

  def self.ransackable_attributes(_auth_object = nil)
    %w[content category_id]
  end
end

app/models/user.rb
class User < ApplicationRecord
    has_many :posts, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :liked_posts, through: :likes, source: :post
    has_many :answers, dependent: :destroy
    has_many :albums, dependent: :destroy
    has_many :messages, dependent: :destroy

    mount_uploader :avatar, AvatarUploader
    
    validates :status, numericality: { greater_than_or_equal_to: 0 }
    validates :email, presence: true
    validates :name, presence: true
    validates :introduction, length: { maximum: 655 }
    
    scope :most_user, -> {
        joins(posts: :answers)
            .select("users.name")
            .where("answers.answer_select = '0'")
            .group('users.name')
            .order("COUNT(posts.user_id) DESC")
            .first
    }
    
    class << self
        def find_or_create_from_auth_hash(auth_hash)
            user_params = user_params_from_auth_hash(auth_hash)
            find_or_create_by(email: user_params[:email]) do |user|
                user.update(user_params)
            end
        end
            
      private
    
        def user_params_from_auth_hash(auth_hash)
        {
            name: auth_hash.info.name,
            email: auth_hash.info.email,
            image: auth_hash.info.image,
        }
        end
    end

    def own?(object)
        id == object.user_id
    end

    def like(post)
        liked_posts << post
    end

    def unlike(post)
        liked_posts.destroy(post)
    end

    def like?(post)
        liked_posts.include?(post)
    end

    def calculate_status
        self.status =  0 + answers.yes_count
        save!
    end

    def has_yes?
        self.answers.exists?(answer_select: "yes")
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
    def translation_class_name(name)
        if name == "食事"
            name.gsub(name, "eat")
        elsif name == "保育園・幼稚園"
            name.gsub(name, "school")
        elsif name == "義理母・義理父"
            name.gsub(name, "mother_in_law")
        elsif name == "健康・病気・怪我"
            name.gsub(name, "sickness")
        elsif name == "妻・夫"
            name.gsub(name, "wife-husband")
        elsif name == "友人"
            name.gsub(name, "friend")
        elsif name == "乳児期"
            name.gsub(name, "baby")
        elsif name == "幼児期初期〜後期"
            name.gsub(name, "infant")
        elsif name == "児童期"
            name.gsub(name, "child")
        elsif name == "青年期"
            name.gsub(name, "youth")
        elsif name == "お金"
            name.gsub(name, "money")
        elsif name == "その他"
            name.gsub(name, "others")
        end
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        return unless (user_id = session[:user_id])
    
        @current_user ||= User.find_by(id: user_id)
    end
    
    def log_in(user)
        session[:user_id] = user.id
    end

    def log_out
        session.delete(:user_id)
        @current_user = nil
    end

    def logged_in?
        !current_user.nil?
    end
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>子育てマッチング</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="turbo-visit-control" content="reload">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Zen+Maru+Gothic&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.css">
    <script src="https://unpkg.com/swiper/swiper-bundle.js"></script>
    <%= turbo_include_tags %>
    <%= display_meta_tags(default_meta_tags) %>
    
    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-G1NWSGZLB5"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', 'G-G1NWSGZLB5');
    </script>
    
  </head>

  <body class="flex-grow overflow-y-auto">
    <div class="wrapper">
      <% if logged_in? %>
        <%= render 'shared/header' %>
      <% else %>
        <%= render 'shared/before_login_header' %>
      <% end %>
      <div id="flash" class="flash">
        <%= render 'shared/flash_message' %>
      </div>
        <%= yield %>
      <%= render 'shared/footer' %>
    </div>
    <%= turbo_frame_tag "modal" %>
  </body>
</html>

app/views/shared/_before_login_header.html.erb
<nav class="relative w-full mx-auto px-4 bg-gray-300 sm:flex sm:items-center sm:justify-between sm:px-6 lg:px-8" aria-label="Global">
    <div class="flex items-center">
        <button>
            <div class="sm:flex items-center gap-x-2-medium font">
                <%= button_to "/auth/google_oauth2", method: :post, data: { turbo: false }, class: "login flex items-center gap-x-2 font-medium text-gray-500 hover:text-blue-600 sm:border-l sm:border-gray-300 sm:my-6 sm:pl-6 dark:border-gray-700 dark:text-gray-400 dark:hover:text-blue-500" do %>
                    <i class="fa-solid fa-circle-user ml-2 w-10 h-10"></i>
                    <%= t('defaults.login') %>
                <% end %>
            </div>
        </button>
    </div>
</nav>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div class="alert alert-error bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative">
        <ul>
        <% object.errors.full_messages.each do |message|%>
            <li><%= message %></li>
        <% end %>
        </ul>
    </div>
<% end %>

app/views/shared/_flash_message.html.erb
<div class="fixed top-0 left-0 right-0 flex items-center justify-center pointer-events-none">
    <% flash.each do |type, message| %>
        <div class="flash_message" data-controller="removals" data-action="animationend->removals#remove">
            <div class="sm:w-full <%= flash_class(type) %> py-4 px-6">
                <span class="block sm:inline"><%= message %></span>
            </div>
        </div>
    <% end %>
</div>

app/views/shared/_footer.html.erb
<footer class="mt-5 bg-gray-300 py-10 px-4 sm:px-6 lg:px-8 mx-auto">
    <div class="text-center">
        <div class="mt-3">
            <p class="text-gray-500">© 2023.kosodatemindchecker</p>
        </div>
        <%= link_to (t 'defaults.form'), 'https://forms.gle/8VRnKLzHFmY2MrYW8', class: "flex items-center gap-x-3.5 py-2 px-3 rounded-md text-sm text-gray-800 hover:bg-gray-100 focus:ring-2 focus:ring-blue-500 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-gray-300"%>
        <%= link_to t('tops.terms.title'), terms_path, class: "flex items-center gap-x-3.5 py-2 px-3 rounded-md text-sm text-gray-800 hover:bg-gray-100 focus:ring-2 focus:ring-blue-500 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-gray-300"%>
        <%= link_to t('tops.privacy.title'), privacy_path, class: "flex items-center gap-x-3.5 py-2 px-3 rounded-md text-sm text-gray-800 hover:bg-gray-100 focus:ring-2 focus:ring-blue-500 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-gray-300"%>
    </div>
</footer>

app/views/shared/_header.html.erb
<nav class="relative w-full mx-auto px-4 bg-gray-300 sm:flex sm:items-center sm:justify-between sm:px-6 lg:px-8" aria-label="Global">
    <div class="flex items-center"> 
        <div class="flex items-center justify-between">
            <div class="hs-dropdown [--strategy:static] sm:[--strategy:fixed] [--adaptive:none] sm:[--trigger:hover] sm:py-4">
                <div class="dropdown-user">
                    <% if current_user.avatar.present? %>
                        <%= image_tag current_user.avatar.url, class: "mr-4 inline-block w-20 h-20 rounded-full"%>
                    <% elsif current_user.image.present? %> 
                        <%= image_tag current_user.image, class: "mr-4 inline-block  w-20 h-20 rounded-full" %>
                    <% else %>
                        <span class="mr-4 inline-block  w-20 h-20 bg-gray-100 rounded-full overflow-hidden">
                            <svg class="h-full w-full text-gray-300" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <rect x="0.62854" y="0.359985" width="15" height="15" rx="7.5" fill="white"/>
                                <path d="M8.12421 7.20374C9.21151 7.20374 10.093 6.32229 10.093 5.23499C10.093 4.14767 9.21151 3.26624 8.12421 3.26624C7.0369 3.26624 6.15546 4.14767 6.15546 5.23499C6.15546 6.32229 7.0369 7.20374 8.12421 7.20374Z" fill="currentColor"/>
                                <path d="M11.818 10.5975C10.2992 12.6412 7.42106 13.0631 5.37731 11.5537C5.01171 11.2818 4.69296 10.9631 4.42107 10.5975C4.28982 10.4006 4.27107 10.1475 4.37419 9.94123L4.51482 9.65059C4.84296 8.95684 5.53671 8.51624 6.30546 8.51624H9.95231C10.7023 8.51624 11.3867 8.94749 11.7242 9.62249L11.8742 9.93184C11.968 10.1475 11.9586 10.4006 11.818 10.5975Z" fill="currentColor"/>
                            </svg>
                        </span>
                    <% end %>
                </div>
                <div class="hs-dropdown-menu absolute sm:w-72 transition-[opacity,margin] duration-[0.1ms] sm:duration-[150ms] hs-dropdown-open:opacity-100 opacity-0 sm:w-48 hidden z-10 bg-white sm:shadow-md rounded-lg p-2 dark:bg-gray-800 sm:dark:border dark:border-gray-700 dark:divide-gray-700 before:absolute top-auto sm:border before:-top-5 before:left-0 before:w-full before:h-5 font">
                    <%= link_to  t('profiles.show.title'), edit_profile_path, class: "flex items-center gap-x-3.5 py-2 px-3 rounded-md text-sm text-gray-800 hover:bg-gray-100 focus:ring-2 focus:ring-blue-500 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-gray-300"%> 
                    <%= button_to (t 'defaults.logout'), log_out_path, method: :delete, data: { turbo: false }, class: "flex items-center gap-x-3.5 py-2 px-3 rounded-md text-sm text-gray-800 hover:bg-gray-100 focus:ring-2 focus:ring-blue-500 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-gray-300"%>
                </div>
            </div>
            <%= link_to start_questions_path, data: { turbo: false }, class: "mr-2 w-20 h-30 rounded-full" do %>
                <%= image_tag '3.png', class: "mr-2 w-20 h-30 rounded-full" %>
            <% end %>
            <%= link_to posts_path, class: "mr-2 w-20 h-30 rounded-full" do %>
                <%=image_tag '2.png', class: "mr-2 w-20 h-30 rounded-full" %>
            <% end %>
            <div class="hs-dropdown [--strategy:static] sm:[--strategy:fixed] [--adaptive:none] sm:[--trigger:hover] sm:py-4">
                <div class="dropdown-album">
                    <%=image_tag '1.png', class: "mr-2 w-20 h-30 rounded-full" %>
                </div>
                <div class="hs-dropdown-menu absolute sm:w-72 transition-[opacity,margin] duration-[0.1ms] sm:duration-[150ms] hs-dropdown-open:opacity-100 opacity-0 sm:w-48 hidden z-10 bg-white sm:shadow-md rounded-lg p-2 dark:bg-gray-800 sm:dark:border dark:border-gray-700 dark:divide-gray-700 before:absolute top-auto sm:border before:-top-5 before:left-0 before:w-full before:h-5 font">
                    <%= link_to t('albums.index.title'), albums_path, class: "flex items-center gap-x-3.5 py-2 px-3 rounded-md text-sm text-gray-800 hover:bg-gray-100 focus:ring-2 focus:ring-blue-500 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-gray-300" %>
                    <%= link_to t('albums.new.title'), new_album_path, data: { turbo_frame: "modal" }, class: "flex items-center gap-x-3.5 py-2 px-3 rounded-md text-sm text-gray-800 hover:bg-gray-100 focus:ring-2 focus:ring-blue-500 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-gray-300" %>
                </div>
            </div>
        </div>
    </div>
</nav>