config/routes.rb
Rails.application.routes.draw do
  
  root 'tops#index'
  get '/privacy', to: 'tops#privacy'
  get '/terms', to: 'tops#terms'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  delete 'log_out', to: 'sessions#destroy', as: 'log_out'

  resources :users, only: %i[show]
  resources :sessions, only: %i[create destroy]
  resource :profile, only: %i[show edit update]
  
  resources :posts do
    resource :like, only: %i[create destroy]
    collection do
      get 'search'
      get 'category/:category_id', action: :category, as: :category
    end
    member do
      get 'channel'
    end
    resources :answers, only: %i[create]
  end
  resources :questions, only: %i[show] do
    get 'random', on: :collection, to: 'questions#random'
    get 'start', on: :collection, to: 'questions#start'
  end
  resources :albums
  mount ActionCable.server => '/cable'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :likes, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :answers
  

  validates :content, presence: true, length: { maximum: 255 }
  validates :user_id, presence: true

  def self.ransackable_attributes(_auth_object = nil)
    %w[content category_id]
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_q, only: %i[index search]
  before_action :find_post, only: %i[edit update destroy]

  def index
    @q = Post.ransack(params[:q])
    @selected_category = Category.find(params[:q][:category_id_eq]) if params[:q] && params[:q][:category_id_eq]
    @posts = @q.result(distinct: true).includes(:user, :category).order(created_at: :desc).page(params[:page]).per(5)
    
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      category_id = params[:post][:category_id]
      category = Category.find(category_id)
      @post.category = category
      redirect_to posts_path, success: t('defaults.message.created', item: Post.model_name.human)
    else
      flash.now[:error] = t('defaults.message.not_created', item: Post.model_name.human)
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit; end

  def update
    if @post.update(post_params)
      redirect_to posts_path, success: t('defaults.message.updated', item: Post.model_name.human)
    else
      flash.now[:error] = t('defaults.message.not_updated', item: Post.model_name.human)
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post.destroy!
    flash.now[:success] = t('defaults.message.deleted', item: Post.model_name.human)
  end
  
  def likes
    @like_post = current_user.liked_posts.includes(:user).order(created_at: :desc)
  end

  def search
    @q = Post.ransack(params[:q])
    @results = @q.result
    if params[:q] && params[:q][:category_id_eq].present?
      @selected_category = Category.find(params[:q][:category_id_eq])
    end
    @posts = @q.result(distinct: true).includes(:user, :category).order(created_at: :desc).page(params[:page]).per(6)
  end

  def category
    category_id = params[:category_id]
    @category = Category.find(category_id)
    @posts = @category.posts.includes(:user).order(created_at: :desc).page(params[:page]).per(8)
  end

  def channel
    @room = Post.find(params[:id])
    @messages = @room.messages
  end

  private

  def post_params
    params.require(:post).permit(:content, :category_id)
  end

  def find_post
    @post = current_user.posts.find(params[:id])
  end

  def set_q
    @set_q = Post.ransack(params[:q])
    @set_q_post = @set_q.result(distinct: true).order(created_at: :desc).page(params[:page])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
    def translation_class_name(name)
        if name == "食事"
            name.gsub(name, "eat")
        elsif name == "保育園・幼稚園"
            name.gsub(name, "school")
        elsif name == "義理母・義理父"
            name.gsub(name, "mother_in_law")
        elsif name == "健康・病気・怪我"
            name.gsub(name, "sickness")
        elsif name == "妻・夫"
            name.gsub(name, "wife-husband")
        elsif name == "友人"
            name.gsub(name, "friend")
        elsif name == "乳児期"
            name.gsub(name, "baby")
        elsif name == "幼児期初期〜後期"
            name.gsub(name, "infant")
        elsif name == "児童期"
            name.gsub(name, "child")
        elsif name == "青年期"
            name.gsub(name, "youth")
        elsif name == "お金"
            name.gsub(name, "money")
        elsif name == "その他"
            name.gsub(name, "others")
        end
    end
end

app/views/posts/_crub_menu.html.erb
<%= link_to edit_post_path(post), 
    id: "button-edit-#{post.id}",
    data: { turbo_frame: "modal" } do %>
    <span class="icon-link mr-4">
        <i class="fa-solid fa-pen" style="color: #adafb3;"></i>
    </span>    
<% end %>
<%= button_to post_path(post),
    method: :delete,
    id: "button-delete-#{post.id}", 
    form: { data: { turbo_confirm: t('defaults.message.delete_confirm') }} do %>   
    <span class="icon-link">
        <i class="fa-solid fa-trash" style="color: #adafb3;"></i>
    </span>   
<% end %>
    

app/views/posts/_form.html.erb
<%= form_with model: post, local: true, data: { turbo: false } do |f| %>
    <%= render 'shared/error_messages', object: f.object %> 
    <div class="max-w-[85rem] px-4 py-10 sm:px-6 lg:px-8 lg:py-14 mx-auto">
        <div class="mx-auto max-w-2xl">
            <div class="text-center">
                <h2 class="text-xl text-gray-800 font-bold sm:text-3xl dark:text-gray-800 font">
                    <%= t('posts.new.title') %>
                </h2>
            </div>
            <!-- Card -->
            <div class="mt-5 p-4 relative z-10 bg-white border rounded-xl sm:mt-10 md:p-10 dark:bg-gray-800 dark:border-gray-700">
                <form>
                    <div class="mb-4 sm:mb-8">
                        <%= f.label :category, Post.human_attribute_name(:category), class: "block mb-2 text-sm font-bold dark:text-white" %>
                        <%= f.collection_select(:category_id,  Category.all, :id, :name, { :prompt  => '選択してください' }, { :class  => "py-3 px-4 pr-9 block w-full border-gray-200 rounded-md text-sm focus:border-blue-500 focus:ring-blue-500 dark:bg-slate-900 dark:border-gray-700 dark:text-gray-400"}) %> 
                    </div>
                    <div>
                        <%= f.label :content, Post.human_attribute_name(:content), class: "block mb-2 text-sm font-bold dark:text-white" %>
                        <div class="mt-1">
                            <%= f.text_area :content, class: "py-3 px-4 block w-full border-gray-200 rounded-md text-sm focus:border-blue-500 focus:ring-blue-500 sm:p-4 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400", row: "3" %>
                        </div>
                    </div>
                    <div class="mt-6 grid">
                        <button type="submit" class="py-3 px-4 inline-flex justify-center items-center gap-2 rounded-md border border-transparent font-semibold bg-yellow-500 text-white hover:bg-gray-400 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 transition-all dark:focus:ring-offset-gray-800">
                            <%= t('defaults.register') %>
                        </button>
                    </div>
                </form>
            </div>
            <!-- End Card -->
        </div>
    </div>
<% end %>
<!-- End Comment Form -->

app/views/posts/_like.html.erb
<%= turbo_frame_tag 'like_count' do %>
    <%= link_to post_like_path(post_id: post.id),
                class: "like_button",
                data: { turbo_method: :post } do %>
        <div class="flex items-center">
            <i class="fa-regular fa-face-meh-blank custom-icon" style="color: #adafb3;"></i>
            <span class="like-count dark:text-white"><%= post.likes.count %></span>
        </div>
    <% end %>
<% end %>

app/views/posts/_like_button.erb
<%= turbo_frame_tag "like_button_#{post.id}" do %>    
    <% if current_user.like?(post) %>
        <%= render 'posts/unlike', { post: post } %>
    <% else %>
        <%= render 'posts/like', { post: post } %>
    <% end %>
<% end %>

app/views/posts/_modal.html.erb
<%= turbo_frame_tag "modal" do %>
    <div class="fixed inset-0 flex items-center justify-center z-50 overflow-y-auto" data-controller="comment-modal" data-comment-modal-target="modal">
        <div class="fixed inset-0 bg-black opacity-50"></div>
        <div class="modal-container bg-white w-96 p-4 rounded-lg shadow-lg z-50" data-comment-modal-target="content">
            <div class="modal-content max-h-screen overflow-y-auto">
                <!-- モーダルのコンテンツ -->
                <%= yield %>  
                <div id="flash" class="flash">
                    <%= render 'shared/flash_message' %>
                </div>     
                <div class="bg-gray-50 px-4 py-3 sm:px-6 sm:flex sm:flex-row-reverse">
                <!-- モーダル閉じるボタン -->
                    <button type="button" data-action="click->comment-modal#close"  class="w-full inline-flex justify-center rounded-md border border-transparent shadow-sm px-4 py-2 bg-indigo-600 text-base font-medium text-white hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 sm:ml-3 sm:w-auto sm:text-sm">
                        <%= t('defaults.close') %>
                    </button>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/posts/_post.html.erb
<div class="max-w-sm bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
    <div class="flex flex-col post px-6 py-4">
        <%= link_to channel_post_path(post), data: { turbo: false }, class: "block h-full p-6 flex items-center gap-x-3" do %>
            <span class="font-semibold text-brack dark:text-gray-200">
                <div id="messages" data-post-id="<%= post.id %>">
                    <%= post.content %>
                </div>
            </span>  
        <% end %>
        <div class="flex justify-between">
            <%= link_to user_path(post.user), class: "block h-full p-6 flex items-center gap-x-3",  data: { turbo: false } do %>
                <% if post.user.avatar.present? %>
                    <%= image_tag post.user.avatar.url, class: "inline-block w-10 h-10 rounded-full"%>
                <% elsif post.user.image.present? %> 
                    <%= image_tag post.user.image, class: "inline-block w-10 h-10 rounded-full"%>
                <% else %>
                    <%= image_tag 'sample.jpg', class: "inline-block w-10 h-10 rounded-full" %>
                <% end %>
                <div class="grow">
                    <span class="block text-sm font-semibold text-gray-800 dark:text-gray-200"><%= post.user.name %></span>
                </div>
            <% end %>
            <span class="text-sm text-gray-600 dark:text-gray-400"></span>
                <div class="flex items-center mr-4">
                    <% if current_user.own?(post) %>
                        <%= render 'crub_menu', post: post %>
                    <% end %>
                </div>
            </span>
            <div class="flex items-center mr-4">
                <%= render 'like_button', post: post %>
            </div>
        </div>
    </div>
    <div class="flex justify-between pt-4 pb-2">
        <%= link_to category_posts_path(category_id: post.category.id) do %>
            <span class="<%= translation_class_name(post.category.name) %> inline-flex items-center gap-1.5 py-2 px-2 rounded-full text-xs font-medium bg-green-100 text-black-800 dark:bg-green-900 dark:text-green-200 ml-6" style="color: black;">
                <%= post.category.name %>
            </span>
        <% end %>
        
        <%= link_to channel_post_path(post), data: { turbo: false }, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 border border-blue-700 rounded mr-4" do %>
            トーク
        <% end %> 
    </div>
</div>

app/views/posts/_shared.html.erb
<div>
    <div class="flex items-center justify-center">
        <%= link_to request.referer, class: "py-3 px-4 inline-flex justify-center items-center gap-2 rounded-md border border-transparent font-semibold bg-gray-500 text-white hover:bg-gray-600 focus:outline-none focus:ring-2 focus:ring-gray-500 focus:ring-offset-2 transition-all text-sm dark:bg-gray-700 dark:hover:bg-gray-600 dark:focus:ring-offset-gray-800" do %>
            <%= t('defaults.back') %>
        <% end %>
    </div>
    <div class="flex flex-wrap mt-4">
        <%= render @posts %>
    </div>
    <div class="flex justify-start mt-4">
        <%= paginate @posts, theme: 'user' %> 
    </div> 
</div>

app/views/posts/_unlike.html.erb
<%= turbo_frame_tag 'like_count' do %>
    <%= link_to post_like_path(post_id: post.id, id: current_user.likes.find_by(post_id: post.id)),
                data: { turbo_method: :delete },
                class: "unlike_button block text-sm text-black-500" do %> 
        <div class="flex items-center">
            <i class="fa-regular fa-face-smile-beam" style="color: #c723a9;"></i>
            <span class="like-count dark:text-white"><%= post.likes.count %></span>
        </div>
    <% end %>
<% end %>

app/views/posts/category.html.erb
<turbo-frame id="comment-list">
    <%= render 'shared', @post %>
</turbo-frame>

app/views/posts/channel.html.erb
<div class="channel bg-green-50" style="background-image: url(<%= asset_path('channel_04.png') %>)">
    <div class="flex justify-center">
        <form class="mt-6">
            <%= label_tag :content, '', class: 'block text-gray-700' %>
            <input type="text" data-behavior="room_speaker" class="py-2 px-3 border border-gray-300 rounded-lg shadow-sm focus:ring focus:ring-blue-200 focus:outline-none" placeholder="メッセージ入力">
        </form>
    </div>
    <div class="flex-1 p:2 sm:p-6 justify-between flex flex-col h-screen">
        <div id='messages' data-room_id="<%= @room.id %>" class="flex flex-col space-y-4 p-3 overflow-y-auto scrollbar-thumb-blue scrollbar-thumb-rounded scrollbar-track-blue-lighter scrollbar-w-2 scrolling-touch">
            <%= render @messages %>
        </div>
    </div>
    
</div>

app/views/posts/edit.html.erb
<%= render "modal" do %>
    <%= render 'form', { post: @post } %>
<% end %>

app/views/posts/index.html.erb
<%= turbo_frame_tag "comment-list" do %> 
    <div class="max-w-[85rem] px-4 py-10 sm:px-6 lg:px-8 lg:py-14 mx-auto">          
        <div class="px-6 py-4 grid gap-3 md:flex md:justify-between md:items-center border-b border-gray-200 dark:border-gray-700">
            <div class="sm:col-span-1 flex">
                <!--カテゴリー検索 -->
                <%= search_form_for @q, url: search_posts_path, class: "flex" do |f| %>
                    <div class="relative flex item-center">
                        <%= f.collection_select(:category_id_eq, Category.all, :id, :name, { include_blank: true }, { class: "py-2 px-3 pl-11 block w-full border-gray-200 shadow-sm rounded-md text-sm focus:z-10 focus:border-blue-500 focus:ring-blue-500 dark:bg-slate-900 dark:border-gray-700 dark:text-gray-400"}) %>
                        <div class="absolute inset-y-0 left-0 flex items-center pointer-events-none pl-4">
                            <svg class="h-4 w-4 text-gray-400" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
                                <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
                            </svg>
                        </div>
                    </div>
                    <%= f.submit t('.search_post'), class: "ml-3 bg-gray-300 hover:bg-gray-500 text-black font-bold py-2 px-4 rounded font" %>
                <% end %>
            </div>
            <div>
                <%= link_to t('.new_post'), new_post_path, data: { turbo_frame: "modal" }, class: "py-3 px-4 inline-flex justify-center items-center gap-2 bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded font" %>
            </div>
        </div> 
        <div class="flex items-center justify-center mt-4" >
            <div class="cardslider">
                <div data-controller="cardslider">
                    <div class="swiper" data-cardslider-target="cardslider">  
                        <div class="swiper-container cardslider">    
                            <div class="swiper-wrapper">
                                <% @posts.each do |post| %>
                                    <div class="swiper-slide">
                                        <%= render post %>
                                    </div>
                                <% end %>
                            </div>
                        </div>
                    </div>
                    <div class="swiper-button-prev"><i class="fa-solid fa-circle-chevron-left" style="color: #a1a5aa;"></i></div>
                    <div class="swiper-button-next"><i class="fa-solid fa-circle-chevron-right" style="color: #a1a5aa;"></i></div>
                </div>
            </div>
        </div>
        <div class="flex justify-start mt-4">
            <%= paginate @posts, theme: 'user' %> 
        </div>
    </div>
<% end %>

app/views/posts/new.html.erb
<%= render "modal" do %>
  <%= render 'form', { post: @post } %>
<% end %>

app/views/posts/search.html.erb
<turbo-frame id="comment-list">
    <% if @posts.present? %>
        <%= render 'shared', @post %>
    <% else %>
        <div class="flex items-center justify-center mt-8">
            <%= link_to request.referer, class: "py-3 px-4 inline-flex justify-center items-center gap-2 rounded-md border border-transparent font-semibold bg-gray-500 text-white hover:bg-gray-600 focus:outline-none focus:ring-2 focus:ring-gray-500 focus:ring-offset-2 transition-all text-sm dark:bg-gray-700 dark:hover:bg-gray-600 dark:focus:ring-offset-gray-800" do %>
                <%= t('defaults.back') %>
            <% end %>
        </div>
        <div class="flex items-center justify-center h-[300px]">
            <div class="w-full max-w-sm bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
                <div class="flex flex-col items-center py-10 ">
                    <p><%= t('.no_result') %></p> 
                </div>
            </div>
        </div>
    <% end %>
</turbo-frame>